//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCO_Generator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CryptoMgrResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CryptoMgrResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POCO_Generator.CryptoMgrResources", typeof(CryptoMgrResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem occurred while building an object to handle crypotgraphic operations. .
        /// </summary>
        internal static string CTOR_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("CTOR_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decrypt an empty or null string..
        /// </summary>
        internal static string DECRYPT_EMPTY_MSG {
            get {
                return ResourceManager.GetString("DECRYPT_EMPTY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unexpected problem while decrypting a string..
        /// </summary>
        internal static string DECRYPT_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("DECRYPT_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unexpected problem while creating an decrypted stream..
        /// </summary>
        internal static string DECRYPTED_STREAM_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("DECRYPTED_STREAM_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot encrypt an empty or null string..
        /// </summary>
        internal static string ENCRYPT_EMPTY_MSG {
            get {
                return ResourceManager.GetString("ENCRYPT_EMPTY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unexpected problem while encrypting a string..
        /// </summary>
        internal static string ENCRYPT_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("ENCRYPT_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unexpected problem while creating an encrypted stream..
        /// </summary>
        internal static string ENCRYPTED_STREAM_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("ENCRYPTED_STREAM_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unexpected problem while hashing a string..
        /// </summary>
        internal static string HASH_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("HASH_UNHANDLED_MSG", resourceCulture);
            }
        }
    }
}
