//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCO_Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POCO_Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandTimeout.
        /// </summary>
        internal static string SETTING_COMMAND_TIMEOUT {
            get {
                return ResourceManager.GetString("SETTING_COMMAND_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionPooling.
        /// </summary>
        internal static string SETTING_CONNECTION_POOLING {
            get {
                return ResourceManager.GetString("SETTING_CONNECTION_POOLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionRetryCount.
        /// </summary>
        internal static string SETTING_CONNECTION_RETRY_COUNT {
            get {
                return ResourceManager.GetString("SETTING_CONNECTION_RETRY_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionRetryInterval.
        /// </summary>
        internal static string SETTING_CONNECTION_RETRY_INTERVAL {
            get {
                return ResourceManager.GetString("SETTING_CONNECTION_RETRY_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionTimeout.
        /// </summary>
        internal static string SETTING_CONNECTION_TIMEOUT {
            get {
                return ResourceManager.GetString("SETTING_CONNECTION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBApplicationName.
        /// </summary>
        internal static string SETTING_DB_APPLICATION_NAME {
            get {
                return ResourceManager.GetString("SETTING_DB_APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBPassword.
        /// </summary>
        internal static string SETTING_DB_PASSWORD {
            get {
                return ResourceManager.GetString("SETTING_DB_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBPortNumber.
        /// </summary>
        internal static string SETTING_DB_PORT_NUMBER {
            get {
                return ResourceManager.GetString("SETTING_DB_PORT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBUserName.
        /// </summary>
        internal static string SETTING_DB_USER_NAME {
            get {
                return ResourceManager.GetString("SETTING_DB_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugLogOptions.
        /// </summary>
        internal static string SETTING_DEBUG_LOG_OPTIONS {
            get {
                return ResourceManager.GetString("SETTING_DEBUG_LOG_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultDB.
        /// </summary>
        internal static string SETTING_DEFAULT_DB {
            get {
                return ResourceManager.GetString("SETTING_DEFAULT_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastDBServer.
        /// </summary>
        internal static string SETTING_LAST_DB_SERVER {
            get {
                return ResourceManager.GetString("SETTING_LAST_DB_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseWindowsAuthentication.
        /// </summary>
        internal static string SETTING_USE_WINDOWS_AUTHENTICATION {
            get {
                return ResourceManager.GetString("SETTING_USE_WINDOWS_AUTHENTICATION", resourceCulture);
            }
        }
    }
}
